[package]
name = "freetype2"
version = "2.14.3"
description = "A library which allows applications to properly render TrueType fonts"
url = "https://downloads.sourceforge.net/freetype/freetype-2.14.3.tar.xz"
md5 = "5e78e6fdce5a61d3075e4c25e9852f84"
source_dir = "freetype-2.14.3"

[dependencies]
requires = ["libpng", "which"]

[build]
system = "autotools"
configure = '''
    --prefix=/usr            \
    --disable-static         \
    --enable-freetype-config \
    --with-harfbuzz=dynamic
'''

[hooks]
pre_configure = '''
sed -ri "s:.*(AUX_MODULES.*valid):\1:" modules.cfg &&

sed -r "s:.*(#.*SUBPIXEL_RENDERING) .*:\1:" \
    -i include/freetype/config/ftoption.h
'''
