[package]
name = "starship"
version = "1.25.1"
description = "The minimal, blazing-fast, and infinitely customizable prompt for any shell!"
url = "https://github.com/starship/starship/releases/download/v1.25.1/starship-x86_64-unknown-linux-gnu.tar.gz"
sha256 = "4488c11ca632327d1f1f16fb2f102c0646094c35479cd5435991385da43c61ac"

[build]
system = "custom"
install = "install -Dm755 starship $DESTDIR/usr/bin/starship"
