[package]
name = "libidn2"
version = "2.3.8"
description = "libidn2 is a package designed for internationalized string handling based on standards from the Internet Engineering Task Force (IETF)'s IDN working group, designed for internationalized domain names."
url = "https://ftpmirror.gnu.org/libidn/libidn2-2.3.8.tar.gz"
md5 = "a8e113e040d57a523684e141970eea7a"

[dependencies]
requires = ["libunistring"]

[build]
system = "autotools"
configure = "--prefix=/usr --disable-static"
