[package]
name = "wget"
version = "1.25.0"
description = "A utility useful for non-interactive downloading of files from the Web"
url = "https://ftpmirror.gnu.org/wget/wget-1.25.0.tar.gz"
md5 = "c70ba58b36f944e8ba1d655ace552881"

[dependencies]
required = ["libpsl"]

[build]
system = "autotools"
configure = '''
    --prefix=/usr      \
    --sysconfdir=/etc  \
    --with-ssl=openssl
'''
