[package]
name = "p11-kit"
version = "0.26.2"
description = "Provides a way to load and enumerate PKCS #11 modules"
url = "https://github.com/p11-glue/p11-kit/releases/download/0.26.2/p11-kit-0.26.2.tar.xz"
md5 = "99edde5f38697ed2d47c55544347be4e"

[dependencies]
requires = ["libtasn1"]

[build]
system = "meson"
configure = "--prefix=/usr --buildtype=release -D trust_paths=/etc/pki/anchors"

install = """
DESTDIR=${DESTDIR} ninja install
ln -sfv /usr/libexec/p11-kit/trust-extract-compat ${DESTDIR}/usr/bin/update-ca-certificates
"""

[hooks]
pre_configure = """
sed '20,$ d' -i trust/trust-extract-compat &&
cat >> trust/trust-extract-compat << "EOF"
# Copy existing anchor modifications to /etc/ssl/local
/usr/libexec/make-ca/copy-trust-modifications
# Update trust stores
/usr/sbin/make-ca -r
EOF
"""

post_install = "ln -sfv ./pkcs11/p11-kit-trust.so /usr/lib/libnssckbi.so"
