[package]
name = "docbook-xsl-nons"
version = "1.79.2"
description = "XSL stylesheets for performing transformations on XML DocBook files"
url = "https://github.com/docbook/xslt10-stylesheets/releases/download/release/1.79.2/docbook-xsl-nons-1.79.2.tar.bz2"
sha256 = "ee8b9eca0b7a8f89075832a2da7534bce8c5478fc8fc2676f512d5d87d832102"

[dependencies]
requires = ["libxml2"]

[source]
patches = ["docbook-xsl-nons-1.79.2-stack_fix-1.patch"]

[build]
system = "custom"
script = "install.sh"
