[package]
name = "nss"
version = "3.120.1"
description = "A set of libraries designed to support cross-platform development of security-enabled client and server applications"
url = "https://archive.mozilla.org/pub/security/nss/releases/NSS_3_120_1_RTM/src/nss-3.120.1.tar.gz"
md5 = "c9642ff2241aa38c9e81589641652a50"

[dependencies]
requires = ["nspr"]

[source]
patches = ["nss-standalone-1.patch"]

[build]
system = "make"
make = '''
cd nss
make BUILD_OPT=1 \
  NSPR_INCLUDE_DIR=/usr/include/nspr \
  USE_SYSTEM_ZLIB=1 \
  ZLIB_LIBS=-lz \
  NSS_ENABLE_WERROR=0 \
  NSS_USE_SYSTEM_SQLITE=1 \
  $([ $(uname -m) = x86_64 ] && echo USE_64=1)
'''

install = """
cd dist
install -v -m755 -d $DESTDIR/usr/lib
install -v -m755 Linux*/lib/*.so $DESTDIR/usr/lib
install -v -m644 Linux*/lib/{*.chk,libcrmf.a} $DESTDIR/usr/lib

install -v -m755 -d $DESTDIR/usr/include/nss
cp -v -RL {public,private}/nss/* $DESTDIR/usr/include/nss

install -v -m755 -d $DESTDIR/usr/bin
install -v -m755 Linux*/bin/{certutil,nss-config,pk12util} $DESTDIR/usr/bin

install -v -m755 -d $DESTDIR/usr/lib/pkgconfig
install -v -m644 Linux*/lib/pkgconfig/nss.pc $DESTDIR/usr/lib/pkgconfig

ln -sfv ./pkcs11/p11-kit-trust.so $DESTDIR/usr/lib/libnssckbi.so
"""
